oz440:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Effort Controllers ---------------------------------------
  back_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_left_wheel_hinge
    pid: {p: 200.0, i: 0, d: 0.001}
    i_clamp: 100.0
  back_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_right_wheel_hinge
    pid: {p: 200.0, i: 0, d: 0.001}
    i_clamp: 100.0
  front_left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_left_wheel_hinge
    pid: {p: 200.0, i: 0, d: 0.001}
    i_clamp: 100.0
  front_right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_right_wheel_hinge
    pid: {p: 200.0, i: 0, d: 0.001}
    i_clamp: 100.0

#  diff_vel_controller:
#    type: "diff_drive_controller/DiffDriveController"
#    left_wheel: ['front_left_wheel_hinge','back_left_wheel_hinge']
#    right_wheel: ['front_right_wheel_hinge','back_right_wheel_hinge']
#
#    # Base frame_id
#    base_frame_id: footprint #default: base_link
